# Generated by Django 4.2.9 on 2026-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('total_voters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PollingBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('constituency', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_voters', models.IntegerField(default=0)),
                ('is_accessible', models.BooleanField(default=True)),
                ('has_cctv', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['constituency', 'booth_id'],
            },
        ),
    ]
